import { ICompilerID, IListItemData } from './ICompilerRegistry'
import { IProcessedScriptOutput } from '@/lib/IScriptBlock'
import { EditorTheme } from '@/plugins/codemirror/editorThemes'
import { UIThemeType } from '@/lib/uiTheme'

export enum KnownBlockTypes {
    PLAYGROUND = 'PLAYGROUND',
    LIBRARY = 'LIBRARY',
    TEXT = 'TEXT',
    BLOCKHIDDEN = 'BLOCK-hidden',
    BLOCKSTATIC = 'BLOCK-static',
    BLOCK = 'BLOCK',
    DATA = 'DATA',
}

export enum CodeOutputTypes {
    AUTO = 'auto',
    TEXT = 'text',
    JSON = 'json',
    DATA = 'data',
    MAGIC = 'magic',
}

export enum CodeExpansionType {
    LARGE = 2,
    AUTO = 1,
    TINY = 0,
}

export interface IBlockError {
    error: string
    uuid: string
}

export interface IRandomizerSet {
    uuid: string
    values: IRandomizerSetTag[]
}

export interface IRandomizerSetTag {
    tag: string
    value: string
}

export interface IRandomizerSettings {
    active: boolean
    previewIndex: number
    knownTags: string[]
    sets: IRandomizerSet[]
}

export interface IBlockData {
    readonly id: number
    readonly type: KnownBlockTypes
    readonly uuid: string
    readonly name: string
    readonly content: string
    readonly obj: any
    readonly themeForCodeBlock: EditorTheme
}

export interface IGlobalSettings {
    baseurl: string
}

export interface IGlobalState extends IGlobalSettings {
    format_info(text: string): string

    format_error(text: string): string

    /**
     * Seperates an outputObject (like the one you will get in the update-method of a playground handler) into a string and a json object seperated by a magic String. Returns an object that contains
     *  <code>type</code> = <code>'dual'</code> parsed a magic string, <code>'json'</code> parsed as json, <code>'text'</code> plain text
     *  <code>json</code> = the JSON object that was sent after the magicString
     *  <code>text</code> = the String that was sent before the magicString
     * @param {*} outputObject  The outputObject generated by the student code
     * @param {*} type  'auto' = (default, try to determin what kind of output was generated), 'text', 'json' = (force json parsing), 'magic' = (force use of magic string seperator)
     * @param {*} magicString The seperating String. By default it is '\n\n<JSON>\n'
     */
    processMixedOutput(
        outputObject: string[] | string,
        type: CodeOutputTypes,
        magicString?: string,
        resultData?: object | any[]
    ): IProcessedScriptOutput

    mimeType(language: string): string

    knownLanguages(): IListItemData[]

    refreshAllCodeMirrors(): void

    refreshAllCodeMirrorsSync(): void

    itemForValue(items: IListItemData[], value: string): IListItemData
}

export interface ICodeBlockSettingsOptions {
    id: number | string
    language: string
    compiler: ICompilerID
    executionTimeout: number
    maxCharacters: number
    runCode: boolean
    emitAST: boolean
    continuousCompilation: boolean
    enableCompletionInViewMode: boolean
    enableAICompletion: boolean
    messagePassing: boolean
    keepAlive: boolean
    persistentArguments: boolean
    domLibs: string[]
    workerLibs: string[]
    uiTheme: UIThemeType
    outputParser: CodeOutputTypes
    randomizer: IRandomizerSettings
}
