import { CompletionContext, CompletionResult } from '@codemirror/autocomplete'
import { createCompletionResult } from './shared'
import { CompletionItem, CompletionOptions } from './types'

const javaKeywords: CompletionItem[] = [
    {
        label: 'public',
        type: 'keyword',
        info: 'Access modifier that makes an element accessible from any class',
    },
    {
        label: 'private',
        type: 'keyword',
        info: 'Access modifier that makes an element accessible only within its class',
    },
    {
        label: 'protected',
        type: 'keyword',
        info: 'Access modifier that makes an element accessible within package and by subclasses',
    },
    { label: 'class', type: 'keyword', info: 'Declares a class' },
    { label: 'interface', type: 'keyword', info: 'Declares an interface' },
    { label: 'extends', type: 'keyword', info: 'Indicates inheritance from a superclass' },
    { label: 'implements', type: 'keyword', info: 'Indicates implementation of interfaces' },
    { label: 'static', type: 'keyword', info: 'Declares a member that belongs to the type itself' },
    {
        label: 'final',
        type: 'keyword',
        info: 'Declares an element that cannot be changed or inherited from',
    },
    { label: 'abstract', type: 'keyword', info: 'Declares an abstract class or method' },
]

const javaTypes: CompletionItem[] = [
    { label: 'void', type: 'type', info: 'Represents no return value' },
    { label: 'int', type: 'type', info: '32-bit integer' },
    { label: 'long', type: 'type', info: '64-bit integer' },
    { label: 'double', type: 'type', info: '64-bit floating point' },
    { label: 'float', type: 'type', info: '32-bit floating point' },
    { label: 'boolean', type: 'type', info: 'true or false value' },
    { label: 'char', type: 'type', info: '16-bit Unicode character' },
    { label: 'String', type: 'type', info: 'Text string' },
    { label: 'byte', type: 'type', info: '8-bit integer' },
    { label: 'short', type: 'type', info: '16-bit integer' },
    { label: 'Integer', type: 'type', info: 'Wrapper class for int' },
    { label: 'Long', type: 'type', info: 'Wrapper class for long' },
    { label: 'Double', type: 'type', info: 'Wrapper class for double' },
    { label: 'Float', type: 'type', info: 'Wrapper class for float' },
    { label: 'Boolean', type: 'type', info: 'Wrapper class for boolean' },
    { label: 'Character', type: 'type', info: 'Wrapper class for char' },
]

const javaSnippets: CompletionItem[] = [
    {
        label: 'main',
        type: 'snippet',
        detail: 'public static void main(String[] args)',
        info: 'Main method - the entry point of a Java program',
    },
    {
        label: 'sout',
        type: 'snippet',
        detail: 'System.out.println();',
        info: 'Print to standard output',
    },
    {
        label: 'fori',
        type: 'snippet',
        detail: 'for (int i = 0; i < length; i++){ }',
        info: 'For loop using a variable i',
    },
    {
        label: 'forj',
        type: 'snippet',
        detail: 'for (int j = 0; j < length; j++){ }',
        info: 'For loop using a variable j',
    },
    {
        label: 'if',
        type: 'snippet',
        detail: 'if () { }',
        info: 'If statement',
    },
    {
        label: 'while',
        type: 'snippet',
        detail: 'while () { }',
        info: 'While loop',
    },
]

const javaCollections: CompletionItem[] = [
    { label: 'Math', type: 'class', info: 'Utility class for common mathematical operations' },
    { label: 'List<T>', type: 'interface', info: 'Ordered collection interface' },
    { label: 'Map<K, V>', type: 'interface', info: 'Key-value mapping interface' },
    { label: 'Set<T>', type: 'interface', info: 'Collection of unique elements' },
    { label: 'Queue<T>', type: 'interface', info: 'FIFO collection interface' },
    {
        label: 'ArrayList<T>',
        type: 'class',
        info: 'Resizable array implementation',
    },
    { label: 'HashMap<K, V>', type: 'class', info: 'Hash table implementation of Map interface' },
    { label: 'LinkedList<T>', type: 'class', info: 'Doubly-linked list implementation' },
    { label: 'HashSet<T>', type: 'class', info: 'Hash table implementation of Set interface' },
    { label: 'StringBuilder', type: 'class', info: 'Mutable sequence of characters' },
    { label: 'StringBuffer', type: 'class', info: 'Thread-safe mutable sequence of characters' },
    { label: 'Collections', type: 'class', info: 'Utility methods for working with collections' },
    { label: 'Arrays', type: 'class', info: 'Utility methods for array operations' },
]

const javaAPI: CompletionItem[] = [
    {
        label: 'System.out.println()',
        type: 'api',
        info: 'Prints to standard output',
    },
    {
        label: 'System.out.print()',
        type: 'api',
        info: 'Prints to standard output without a newline',
    },
    { label: 'Math.abs(x)', type: 'api', info: 'Returns the absolute value of a number' },
    { label: 'Math.max(v0, v1)', type: 'api', info: 'Returns the larger of two numbers' },
    { label: 'Math.min(v0, v1)', type: 'api', info: 'Returns the smaller of two numbers' },
    {
        label: 'Math.pow(x, e)',
        type: 'api',
        info: 'Returns the value of the first argument raised to the power of the second argument',
    },
    { label: 'Math.sqrt(x)', type: 'api', info: 'Returns the square root of a number' },
    {
        label: 'Math.random()',
        type: 'api',
        info: 'Returns a random number between 0.0 and 1.0 (excluded)',
    },
]

const javaAPIMembers: CompletionItem[] = [
    { label: 'System.out', type: 'property', info: 'Standard output stream' },
    { label: 'System.err', type: 'property', info: 'Standard error stream' },
    { label: 'System.in', type: 'property', info: 'Standard input stream' },
    { label: 'System.currentTimeMillis()', type: 'method' },
    { label: 'System.nanoTime()', type: 'method' },
    { label: 'System.getenv("KEY")', type: 'method', apply: 'System.getenv("")' },
    {
        label: 'System.getProperty("key")',
        type: 'method',
        apply: 'System.getProperty("")',
    },
    { label: 'Math.PI', type: 'constant', info: 'Ratio of circumference to diameter' },
    { label: 'Math.E', type: 'constant', info: 'Euler constant' },
    { label: 'Math.ceil(x)', type: 'method' },
    { label: 'Math.floor(x)', type: 'method' },
    { label: 'Math.round(x)', type: 'method' },
    { label: 'Math.sin(x)', type: 'method' },
    { label: 'Math.cos(x)', type: 'method' },
    { label: 'Math.tan(x)', type: 'method' },
    { label: 'Math.log(x)', type: 'method' },
    { label: 'Math.exp(x)', type: 'method' },
    { label: 'Math.max(a, b)', type: 'method' },
    { label: 'Math.min(a, b)', type: 'method' },
    { label: 'length()', type: 'method', detail: 'String' },
    { label: 'isEmpty()', type: 'method', detail: 'String / List / Map / Set' },
    { label: 'charAt(index)', type: 'method', detail: 'String' },
    { label: 'substring(beginIndex, endIndex)', type: 'method', detail: 'String' },
    { label: 'startsWith(prefix)', type: 'method', detail: 'String' },
    { label: 'endsWith(suffix)', type: 'method', detail: 'String' },
    { label: 'contains(text)', type: 'method', detail: 'String' },
    { label: 'indexOf(text)', type: 'method', detail: 'String' },
    { label: 'trim()', type: 'method', detail: 'String' },
    { label: 'toLowerCase()', type: 'method', detail: 'String' },
    { label: 'toUpperCase()', type: 'method', detail: 'String' },
    { label: 'split(regex)', type: 'method', detail: 'String' },
    { label: 'replace(target, replacement)', type: 'method', detail: 'String' },
    { label: 'Integer.parseInt(text)', type: 'method' },
    { label: 'Double.parseDouble(text)', type: 'method' },
    { label: 'Boolean.parseBoolean(text)', type: 'method' },
    { label: 'Integer.MAX_VALUE', type: 'constant' },
    { label: 'Integer.MIN_VALUE', type: 'constant' },
    { label: 'Long.MAX_VALUE', type: 'constant' },
    { label: 'Long.MIN_VALUE', type: 'constant' },
    { label: 'Double.NaN', type: 'constant' },
    { label: 'Double.POSITIVE_INFINITY', type: 'constant' },
    { label: 'Double.NEGATIVE_INFINITY', type: 'constant' },
    { label: 'add(item)', type: 'method', detail: 'List / Set' },
    { label: 'get(index)', type: 'method', detail: 'List' },
    { label: 'set(index, value)', type: 'method', detail: 'List' },
    { label: 'remove(index)', type: 'method', detail: 'List' },
    { label: 'remove(item)', type: 'method', detail: 'List / Set' },
    { label: 'contains(item)', type: 'method', detail: 'List / Set' },
    { label: 'size()', type: 'method', detail: 'List / Map / Set' },
    { label: 'put(key, value)', type: 'method', detail: 'Map / JsonObject' },
    { label: 'get(key)', type: 'method', detail: 'Map' },
    { label: 'getOrDefault(key, defaultValue)', type: 'method', detail: 'Map' },
    { label: 'remove(key)', type: 'method', detail: 'Map' },
    { label: 'containsKey(key)', type: 'method', detail: 'Map' },
    { label: 'containsValue(value)', type: 'method', detail: 'Map' },
    { label: 'keySet()', type: 'method', detail: 'Map' },
    { label: 'values()', type: 'method', detail: 'Map' },
    { label: 'entrySet()', type: 'method', detail: 'Map' },
    { label: 'offer(item)', type: 'method', detail: 'Queue' },
    { label: 'poll()', type: 'method', detail: 'Queue' },
    { label: 'peek()', type: 'method', detail: 'Queue' },
    { label: 'new ArrayList<>()', type: 'snippet', apply: 'new ArrayList<>()' },
    { label: 'new HashMap<>()', type: 'snippet', apply: 'new HashMap<>()' },
    { label: 'new HashSet<>()', type: 'snippet', apply: 'new HashSet<>()' },
    { label: 'Arrays.asList(...)', type: 'method' },
    { label: 'Arrays.sort(array)', type: 'method' },
    { label: 'Arrays.binarySearch(array, key)', type: 'method' },
    { label: 'Arrays.fill(array, value)', type: 'method' },
    { label: 'Collections.sort(list)', type: 'method' },
    { label: 'Collections.reverse(list)', type: 'method' },
    { label: 'Collections.shuffle(list)', type: 'method' },
    { label: 'Collections.emptyList()', type: 'method' },
    { label: 'Collections.singletonList(item)', type: 'method' },
    { label: 'append(value)', type: 'method', detail: 'StringBuilder' },
    { label: 'insert(index, value)', type: 'method', detail: 'StringBuilder' },
    { label: 'delete(start, end)', type: 'method', detail: 'StringBuilder' },
    { label: 'reverse()', type: 'method', detail: 'StringBuilder' },
    { label: 'toString()', type: 'method', detail: 'StringBuilder / StringBuffer' },
]

const lgdvAPI: CompletionItem[] = [
    { label: 'Canvas', type: 'class', detail: 'de.fau.tf.lgdv.graphics.Canvas' },
    { label: 'Color', type: 'class', detail: 'de.fau.tf.lgdv.graphics.Color' },
    { label: 'Image', type: 'class', detail: 'de.fau.tf.lgdv.graphics.Image' },
    { label: 'KeyEvent', type: 'class', detail: 'de.fau.tf.lgdv.graphics.KeyEvent' },
    { label: 'KeyEventType', type: 'class', detail: 'de.fau.tf.lgdv.graphics.KeyEventType' },
    { label: 'KeyInfo', type: 'class', detail: 'de.fau.tf.lgdv.graphics.KeyInfo' },
    { label: 'Layer', type: 'class', detail: 'de.fau.tf.lgdv.graphics.Layer' },
    { label: 'ModifiersInfo', type: 'class', detail: 'de.fau.tf.lgdv.graphics.ModifiersInfo' },
    { label: 'MouseEvent', type: 'class', detail: 'de.fau.tf.lgdv.graphics.MouseEvent' },
    { label: 'MouseEventType', type: 'class', detail: 'de.fau.tf.lgdv.graphics.MouseEventType' },
    { label: 'MouseInfo', type: 'class', detail: 'de.fau.tf.lgdv.graphics.MouseInfo' },
    { label: 'TickEvent', type: 'class', detail: 'de.fau.tf.lgdv.graphics.TickEvent' },
    {
        label: 'ISOTimestampConverter',
        type: 'class',
        detail: 'de.fau.tf.lgdv.json.ISOTimestampConverter',
    },
    { label: 'JsonArray', type: 'class', detail: 'de.fau.tf.lgdv.json.JsonArray' },
    { label: 'JsonElement', type: 'class', detail: 'de.fau.tf.lgdv.json.JsonElement' },
    { label: 'JsonObject', type: 'class', detail: 'de.fau.tf.lgdv.json.JsonObject' },
    { label: 'JsonObjectable', type: 'class', detail: 'de.fau.tf.lgdv.json.JsonObjectable' },
    { label: 'JsonParser', type: 'class', detail: 'de.fau.tf.lgdv.json.JsonParser' },
    { label: 'JsonSerializer', type: 'class', detail: 'de.fau.tf.lgdv.json.JsonSerializer' },
    { label: 'Version', type: 'class', detail: 'de.fau.tf.lgdv.json.Version' },
    { label: 'Cone', type: 'class', detail: 'de.fau.tf.lgdv.math.Cone' },
    { label: 'Geometry', type: 'class', detail: 'de.fau.tf.lgdv.math.Geometry' },
    { label: 'Helper', type: 'class', detail: 'de.fau.tf.lgdv.math.Helper' },
    { label: 'Int2D', type: 'class', detail: 'de.fau.tf.lgdv.math.Int2D' },
    { label: 'Line2D', type: 'class', detail: 'de.fau.tf.lgdv.math.Line2D' },
    { label: 'Plane', type: 'class', detail: 'de.fau.tf.lgdv.math.Plane' },
    { label: 'Ray', type: 'class', detail: 'de.fau.tf.lgdv.math.Ray' },
    { label: 'Size', type: 'class', detail: 'de.fau.tf.lgdv.math.Size' },
    { label: 'Sphere', type: 'class', detail: 'de.fau.tf.lgdv.math.Sphere' },
    { label: 'Vec2D', type: 'class', detail: 'de.fau.tf.lgdv.math.Vec2D' },
    { label: 'Vec3D', type: 'class', detail: 'de.fau.tf.lgdv.math.Vec3D' },
    { label: 'AnimatedSprite', type: 'class', detail: 'de.fau.tf.lgdv.phaser.AnimatedSprite' },
    {
        label: 'AnimatedSpriteEventHandler',
        type: 'class',
        detail: 'de.fau.tf.lgdv.phaser.AnimatedSpriteEventHandler',
    },
    { label: 'EventHandler', type: 'class', detail: 'de.fau.tf.lgdv.phaser.EventHandler' },
    { label: 'Figure', type: 'class', detail: 'de.fau.tf.lgdv.phaser.Figure' },
    {
        label: 'FigureEventHandler',
        type: 'class',
        detail: 'de.fau.tf.lgdv.phaser.FigureEventHandler',
    },
    { label: 'GameEventHandler', type: 'class', detail: 'de.fau.tf.lgdv.phaser.GameEventHandler' },
    { label: 'MapGame', type: 'class', detail: 'de.fau.tf.lgdv.phaser.MapGame' },

    { label: 'Sprite', type: 'class', detail: 'de.fau.tf.lgdv.phaser.Sprite' },
]

const javaRuntimeClasses: CompletionItem[] = [
    {
        label: 'CodeBlocks',
        type: 'class',
        detail: 'de.fau.tf.lgdv.CodeBlocks',
        info: 'CodeBlocks runtime API',
    },
    {
        label: 'CodeBlocksBaseMessage',
        type: 'class',
        detail: 'de.fau.tf.lgdv.CodeBlocksBaseMessage',
    },
    {
        label: 'CodeBlocksDoubleArrayMessage',
        type: 'class',
        detail: 'de.fau.tf.lgdv.CodeBlocksDoubleArrayMessage',
    },
    {
        label: 'CodeBlocksDoubleMessage',
        type: 'class',
        detail: 'de.fau.tf.lgdv.CodeBlocksDoubleMessage',
    },
    {
        label: 'CodeBlocksEventFunction',
        type: 'class',
        detail: 'de.fau.tf.lgdv.CodeBlocksEventFunction',
    },
    {
        label: 'CodeBlocksIntArrayMessage',
        type: 'class',
        detail: 'de.fau.tf.lgdv.CodeBlocksIntArrayMessage',
    },
    { label: 'CodeBlocksIntMessage', type: 'class', detail: 'de.fau.tf.lgdv.CodeBlocksIntMessage' },
    {
        label: 'CodeBlocksQueryMessage',
        type: 'class',
        detail: 'de.fau.tf.lgdv.CodeBlocksQueryMessage',
    },
    {
        label: 'CodeBlocksStringArrayMessage',
        type: 'class',
        detail: 'de.fau.tf.lgdv.CodeBlocksStringArrayMessage',
    },
    {
        label: 'CodeBlocksStringMessage',
        type: 'class',
        detail: 'de.fau.tf.lgdv.CodeBlocksStringMessage',
    },
    { label: 'CommandBuffer', type: 'class', detail: 'de.fau.tf.lgdv.runtime.CommandBuffer' },
    {
        label: 'NewRemoteObjectMessage',
        type: 'class',
        detail: 'de.fau.tf.lgdv.runtime.NewRemoteObjectMessage',
    },
    {
        label: 'ObjectReplyMessage',
        type: 'class',
        detail: 'de.fau.tf.lgdv.runtime.ObjectReplyMessage',
    },
    { label: 'RemoteObject', type: 'class', detail: 'de.fau.tf.lgdv.runtime.RemoteObject' },
    { label: '@JSCommand', type: 'class', detail: 'de.fau.tf.lgdv.runtime.annotations.JSCommand' },
    { label: '@JSEvent', type: 'class', detail: 'de.fau.tf.lgdv.runtime.annotations.JSEvent' },
    { label: '@JSQuery', type: 'class', detail: 'de.fau.tf.lgdv.runtime.annotations.JSQuery' },
    { label: 'RPCIDMessage', type: 'class', detail: 'de.fau.tf.lgdv.phaser.RPCIDMessage' },
    {
        label: 'RPCNewAnimationMessage',
        type: 'class',
        detail: 'de.fau.tf.lgdv.phaser.RPCNewAnimationMessage',
    },
    { label: 'RPCNewMessage', type: 'class', detail: 'de.fau.tf.lgdv.phaser.RPCNewMessage' },
    { label: 'RPCSpeedMessage', type: 'class', detail: 'de.fau.tf.lgdv.phaser.RPCSpeedMessage' },
    { label: 'RPCTileMessage', type: 'class', detail: 'de.fau.tf.lgdv.phaser.RPCTileMessage' },
]

const lgdvImportSnippets: CompletionItem[] = [
    {
        label: 'import de.fau.tf.lgdv.graphics.*',
        type: 'snippet',
        detail: 'import de.fau.tf.lgdv.graphics.*;',
        apply: 'import de.fau.tf.lgdv.graphics.*;\n',
    },
    {
        label: 'import de.fau.tf.lgdv.phaser.*',
        type: 'snippet',
        detail: 'import de.fau.tf.lgdv.phaser.*;',
        apply: 'import de.fau.tf.lgdv.phaser.*;\n',
    },
    {
        label: 'import de.fau.tf.lgdv.json.*',
        type: 'snippet',
        detail: 'import de.fau.tf.lgdv.json.*;',
        apply: 'import de.fau.tf.lgdv.json.*;\n',
    },
    {
        label: 'import de.fau.tf.lgdv.math.*',
        type: 'snippet',
        detail: 'import de.fau.tf.lgdv.math.*;',
        apply: 'import de.fau.tf.lgdv.math.*;\n',
    },
]

const runtimeImportSnippets: CompletionItem[] = [
    {
        label: 'import de.fau.tf.lgdv.*',
        type: 'snippet',
        detail: 'import de.fau.tf.lgdv.*;',
        apply: 'import de.fau.tf.lgdv.*;\n',
    },
    {
        label: 'import de.fau.tf.lgdv.runtime.*',
        type: 'snippet',
        detail: 'import de.fau.tf.lgdv.runtime.*;',
        apply: 'import de.fau.tf.lgdv.runtime.*;\n',
    },
    {
        label: 'import de.fau.tf.lgdv.runtime.annotations.*',
        type: 'snippet',
        detail: 'import de.fau.tf.lgdv.runtime.annotations.*;',
        apply: 'import de.fau.tf.lgdv.runtime.annotations.*;\n',
    },
]

const lgdvClassMembers: CompletionItem[] = [
    { label: 'Canvas.getScreenDimensions()', type: 'method' },
    { label: 'Canvas.addMouseEventListener(listener)', type: 'method' },
    { label: 'Canvas.addKeyEventListener(listener)', type: 'method' },
    { label: 'Canvas.addTickEventListener(listener)', type: 'method' },
    { label: 'Canvas.enableTicks()', type: 'method' },
    { label: 'Canvas.disableTicks()', type: 'method' },
    { label: 'Canvas.setTickMode(enabled)', type: 'method' },
    { label: 'Canvas.clear()', type: 'method' },
    { label: 'Canvas.clear(color)', type: 'method' },
    { label: 'Canvas.setStrokeStyle(style)', type: 'method' },
    { label: 'Canvas.setFillStyle(style)', type: 'method' },
    { label: 'Canvas.setLineWidth(width)', type: 'method' },
    { label: 'Canvas.setFont(font)', type: 'method' },
    { label: 'Canvas.beginPath()', type: 'method' },
    { label: 'Canvas.closePath()', type: 'method' },
    { label: 'Canvas.stroke()', type: 'method' },
    { label: 'Canvas.fill()', type: 'method' },
    { label: 'Canvas.moveTo(x, y)', type: 'method' },
    { label: 'Canvas.lineTo(x, y)', type: 'method' },
    { label: 'Canvas.fillRect(x, y, w, h)', type: 'method' },
    { label: 'Canvas.strokeRect(x, y, w, h)', type: 'method' },
    { label: 'Canvas.clearRect(x, y, w, h)', type: 'method' },
    { label: 'Canvas.arc(x, y, radius, startAngle, endAngle, anticlockwise)', type: 'method' },
    { label: 'Canvas.fillText(text, x, y)', type: 'method' },
    { label: 'Canvas.strokeText(text, x, y)', type: 'method' },
    { label: 'Canvas.save()', type: 'method' },
    { label: 'Canvas.restore()', type: 'method' },
    { label: 'Canvas.translate(x, y)', type: 'method' },
    { label: 'Canvas.rotate(angle)', type: 'method' },
    { label: 'Canvas.scale(x, y)', type: 'method' },
    { label: 'Canvas.line(x1, y1, x2, y2)', type: 'method' },
    { label: 'Canvas.rectangle(x1, y1, x2, y2, fill)', type: 'method' },
    { label: 'Canvas.circle(x, y, radius, fill)', type: 'method' },
    { label: 'Canvas.drawImage(img, position)', type: 'method' },
    { label: 'Canvas.drawImage(img, position, scale)', type: 'method' },
    // MapGame fields & instance methods
    { label: 'rows', type: 'property', detail: 'MapGame' },
    { label: 'columns', type: 'property', detail: 'MapGame' },
    { label: 'createFigureOnTile(type, c, r)', type: 'method', detail: 'MapGame' },
    { label: 'createSpriteOnTile(type, c, r)', type: 'method', detail: 'MapGame' },
    { label: 'createAnimatedSpriteOnTile(type, c, r)', type: 'method', detail: 'MapGame' },
    { label: 'getFigureStream()', type: 'method', detail: 'MapGame' },
    { label: 'getFigureCount()', type: 'method', detail: 'MapGame' },
    { label: 'getSpriteStream()', type: 'method', detail: 'MapGame' },
    { label: 'getSpriteCount()', type: 'method', detail: 'MapGame' },
    // Sprite fields & instance methods
    { label: 'type', type: 'property', detail: 'Sprite' },
    { label: 'mapGame', type: 'property', detail: 'Sprite' },
    { label: 'getColumn()', type: 'method', detail: 'Sprite' },
    { label: 'getRow()', type: 'method', detail: 'Sprite' },
    { label: 'wasRemoved()', type: 'method', detail: 'Sprite' },
    { label: 'moveToTile(c, r)', type: 'method', detail: 'Sprite' },
    { label: 'moveTo(x, y)', type: 'method', detail: 'Sprite' },
    { label: 'remove()', type: 'method', detail: 'Sprite' },
    // Figure instance methods
    { label: 'walkToTile(c, r)', type: 'method', detail: 'Figure' },
    { label: 'walkTo(x, y)', type: 'method', detail: 'Figure' },
    { label: 'setBaseSpeed(speed)', type: 'method', detail: 'Figure' },
    { label: 'stopWalking()', type: 'method', detail: 'Figure' },
    { label: 'getBaseSpeed()', type: 'method', detail: 'Figure' },
    // AnimatedSprite instance methods
    { label: 'play()', type: 'method', detail: 'AnimatedSprite' },
    { label: 'stop()', type: 'method', detail: 'AnimatedSprite' },
    // Layer fields & instance methods
    { label: 'text', type: 'property', detail: 'Layer' },
    { label: 'className', type: 'property', detail: 'Layer' },
    { label: 'parent', type: 'property', detail: 'Layer' },
    { label: 'isReady()', type: 'method', detail: 'Layer' },
    { label: 'setPosition(position)', type: 'method', detail: 'Layer' },
    { label: 'setSize(size)', type: 'method', detail: 'Layer' },
    { label: 'setVisible(visible)', type: 'method', detail: 'Layer' },
    { label: 'setOpacity(opacity)', type: 'method', detail: 'Layer' },
    { label: 'setBackground(color)', type: 'method', detail: 'Layer' },
    { label: 'setBorderWidth(borderWidth)', type: 'method', detail: 'Layer' },
    { label: 'setBorderColor(borderColor)', type: 'method', detail: 'Layer' },
    { label: 'setText(text)', type: 'method', detail: 'Layer' },
    { label: 'setMarkdown(markdown)', type: 'method', detail: 'Layer' },
    { label: 'setTextColor(color)', type: 'method', detail: 'Layer' },
    { label: 'setFontSize(size)', type: 'method', detail: 'Layer' },
    { label: 'setPadding(all)', type: 'method', detail: 'Layer' },
    // Image fields & instance methods
    { label: 'src', type: 'property', detail: 'Image' },
    { label: 'getWidth()', type: 'method', detail: 'Image' },
    { label: 'getHeight()', type: 'method', detail: 'Image' },
    {
        label: 'draw(position, size)',
        type: 'method',
        detail: 'Image',
        info: 'Overloaded: draw(position, size) or draw(position, scale)',
    },
    // Color fields & instance methods
    { label: 'r', type: 'property', detail: 'Color' },
    { label: 'g', type: 'property', detail: 'Color' },
    { label: 'b', type: 'property', detail: 'Color' },
    { label: 'a', type: 'property', detail: 'Color' },
    { label: 'rgb()', type: 'method', detail: 'Color' },
    { label: 'hsl()', type: 'method', detail: 'Color' },
    { label: 'hsv()', type: 'method', detail: 'Color' },
    { label: 'toRgbaString()', type: 'method', detail: 'Color' },
    { label: 'Color.fromJsonElement(el)', type: 'method' },
    // Vec2D fields & instance methods
    { label: 'x', type: 'property', detail: 'Vec2D / Vec3D / Int2D' },
    { label: 'y', type: 'property', detail: 'Vec2D / Vec3D / Int2D' },
    { label: 'z', type: 'property', detail: 'Vec3D' },
    { label: 'getX()', type: 'method', detail: 'Vec2D' },
    { label: 'getY()', type: 'method', detail: 'Vec2D' },
    { label: 'add(v)', type: 'method', detail: 'Vec2D' },
    { label: 'sub(v)', type: 'method', detail: 'Vec2D' },
    { label: 'mul(f)', type: 'method', detail: 'Vec2D' },
    { label: 'distance(v)', type: 'method', detail: 'Vec2D / Vec3D' },
    // JsonObject instance methods
    { label: 'getInt(key)', type: 'method', detail: 'JsonObject' },
    { label: 'getDouble(key)', type: 'method', detail: 'JsonObject' },
    { label: 'getBoolean(key)', type: 'method', detail: 'JsonObject' },
    { label: 'getString(key)', type: 'method', detail: 'JsonObject' },
    { label: 'getObject(key)', type: 'method', detail: 'JsonObject' },
    { label: 'getArray(key)', type: 'method', detail: 'JsonObject' },
    { label: 'has(key)', type: 'method', detail: 'JsonObject' },
    { label: 'toJson()', type: 'method', detail: 'JsonObject / JsonArray / JsonElement' },
    // JsonArray instance methods
    { label: 'push(value)', type: 'method', detail: 'JsonArray' },
    { label: 'getInt(index, defaultValue)', type: 'method', detail: 'JsonArray' },
    { label: 'getDouble(index, defaultValue)', type: 'method', detail: 'JsonArray' },
    // JsonElement instance methods
    { label: 'getInt()', type: 'method', detail: 'JsonElement' },
    { label: 'getDouble()', type: 'method', detail: 'JsonElement' },
    { label: 'getString()', type: 'method', detail: 'JsonElement' },
    { label: 'getBoolean()', type: 'method', detail: 'JsonElement' },
    { label: 'getObject()', type: 'method', detail: 'JsonElement' },
    { label: 'getArray()', type: 'method', detail: 'JsonElement' },
    { label: 'isNull()', type: 'method', detail: 'JsonElement' },
    // JsonParser static method
    { label: 'JsonParser.parse(json)', type: 'method' },
    // Version fields & instance methods
    { label: 'major', type: 'property', detail: 'Version' },
    { label: 'minor', type: 'property', detail: 'Version' },
    { label: 'patch', type: 'property', detail: 'Version' },
    { label: 'comment', type: 'property', detail: 'Version' },
    { label: 'isAtLeast(other)', type: 'method', detail: 'Version' },
    { label: 'compareTo(other)', type: 'method', detail: 'Version' },
]

const javaRuntimeMembers: CompletionItem[] = [
    { label: 'CodeBlocks.getSessionId()', type: 'method' },
    { label: 'CodeBlocks.getVersion()', type: 'method' },
    { label: 'CodeBlocks.exit(code)', type: 'method' },
    { label: 'CodeBlocks.postResult(json)', type: 'method' },
    { label: 'CodeBlocks.stringify(obj)', type: 'method' },
    { label: 'CodeBlocks.generateQueryId()', type: 'method' },
    { label: 'CodeBlocks.waitForQueryReply(queryId)', type: 'method' },
    { label: 'CodeBlocks.waitForEvent(key)', type: 'method' },
    { label: 'CodeBlocks.sendQuery(cmd, json)', type: 'method' },
    { label: 'CodeBlocks.postMessage(message)', type: 'method' },
    { label: 'CodeBlocks.parseMessageJSON(msg)', type: 'method' },
    { label: 'CodeBlocks.startReceivingEvents(handler)', type: 'method' },
    { label: 'CodeBlocks.stopReceivingEvents()', type: 'method' },
    { label: 'CodeBlocks.createMessage(cmd)', type: 'method' },
    { label: 'CodeBlocks.postQuery(cmd, queryId, value)', type: 'method' },
    { label: 'CommandBuffer.of(obj)', type: 'method' },
    { label: 'CommandBuffer.addEmptyCommand(command)', type: 'method' },
    { label: 'CommandBuffer.addCommand(command, value)', type: 'method' },
    { label: 'CommandBuffer.addNewObject(obj)', type: 'method' },
    { label: 'CommandBuffer.activate()', type: 'method' },
    { label: 'CommandBuffer.deactivate()', type: 'method' },
    { label: 'CommandBuffer.sendCommands()', type: 'method' },
    { label: 'RemoteObject.handleEvent(cmd, json)', type: 'method' },
]

const javaBaseCompletions = [
    ...javaKeywords,
    ...javaTypes,
    ...javaSnippets,
    ...javaCollections,
    ...javaAPI,
    ...javaAPIMembers,
    ...lgdvAPI,
    ...lgdvImportSnippets,
    ...lgdvClassMembers,
]

export function createJavaCompletions(
    context: CompletionContext,
    options?: CompletionOptions
): CompletionResult | null {
    const allCompletions = options?.includeRuntime
        ? [
              ...javaBaseCompletions,
              ...javaRuntimeClasses,
              ...runtimeImportSnippets,
              ...javaRuntimeMembers,
          ]
        : javaBaseCompletions
    return createCompletionResult(context, allCompletions)
}
