import de.fau.tf.lgdv.*;
import org.teavm.jso.JSProperty;
import de.fau.tf.lgdv.runtime.RemoteObject;
import de.fau.tf.lgdv.json.*;
import org.teavm.jso.JSObject;
import java.util.List;
import java.util.ArrayList;
import de.fau.tf.lgdv.math.Vec2D;
import de.fau.tf.lgdv.math.Int2D;